### ISSUE TITLE
Pipeline 1 - Busca de Instrucao em Memoria

### ISSUE THREAD

**Issue by andre-romano** [alr46664/lab4#1]
Implementação da busca de instrução na memória de programa.

Memória de Programa (segmento de programa): 64k x 16 (tamanho minimo).

**Comment by alr46664** [comment]
Esta etapa faz parte da Unidade de Controle. Vide issue [Implementação da Unidade de Controle](https://github.com/alr46664/lab4/issues/12)

**Comment by andre-romano** [comment]
O issue [Implementação - Memoria - Unidade de Leitura e Gravação (com Modos de Endereçamento)](https://github.com/alr46664/lab4/issues/7) esta associado a este problema, logo estou juntando ambos
